### PR TITLE
vote: new(OWNERS): add LucaGuerra to owners

### PR DESCRIPTION
**Pull request by LucaGuerra**
As a Falco core maintainer I would like to propose myself as an approver for this repo to make it easier for the community to update reference docs.

### CODE REVIEW

**Comment by leogr** [comment]
/kind docs

/hold until the vote is complete

+1 from me!

**Comment by leogr** [comment]
cc @falcosecurity/github-maintainers

**Review by leogr — APPROVED** [review]

**Comment by maxgio92** [comment]
+1

**Comment by jasondellaluce** [comment]
+1! Thanks Luca

**Comment by leogr** [comment]
Awesome, we got majority! 

/hold cancel

**Pull request merged**
